/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  royum
 * Created: 31 oct 2025
 */

--BORRAR DE HIJAS A PADRES
drop table if exists ALERTA;
drop table if exists TRANSACCION;
drop table if exists META_AHORRO;
drop table if exists OBLIGACION_FIJA;
drop table if exists PRESUPUESTO_DETALLE;
drop table if exists SUBCATEGORIA;
drop table if exists CATEGORIA;
drop table if exists PRESUPUESTO;
drop table if exists USUARIOS;

--TABLAS CON SUS ATRIBUTOSSSSZZZZ
create table USUARIOS 
(
  
    Id_usuario bigint generated by default as identity primary key,
    Nombre_usuario varchar(70) not null,
    Apellido_usuario varchar(70) not null,
    Correo_electronico varchar(70) not null unique,
    Fecha_Registro timestamp not null,
    Salario_mensual_base decimal(14,2)not null,--es 14,2 para controlar bien los montos
    Estado_usuario boolean default true

);

create table PRESUPUESTO
(

    Id_presupuesto bigint generated by default as identity primary key,
    Id_usuario bigint not null,
    Nombre_descriptivo varchar(500) not null,
    Anios_de_inicio smallint not null,
    Mes_de_inicio  tinyint not null,--1...12
    Total_de_ingresos decimal(14,2) not null,
    Total_de_gastos decimal(14,2) not null,
    Total_de_ahorro decimal(14,2) not null,
    Fecha_hora_creacion timestamp not null,
    Estado_presupuesto varchar(20)not null
    
);

create table CATEGORIA
(

    Id_categoria bigint generated by default as identity primary key,
    Nombre varchar(50) not null,
    Descripcion_detallada varchar(500),
    Tipo_de_categoria varchar(15) not null --ingreso|gasto|ahorro

);

create table SUBCATEGORIA
(

    Id_subcategoria bigint generated by default as identity primary key,
    Id_categoria bigint not null,
    Nombre_subcategoria varchar(70) not null,
    Estado boolean  not null default true,
    Por_defecto boolean not null default false

);

create table PRESUPUESTO_DETALLE
(

    Id_presupuesto_detalle bigint  generated by default as identity primary key,
    Id_presupuesto bigint not null,
    Id_subcategoria bigint not null,
    Monto_mensual decimal(14,2)not null,
    Justificacion_del_monto varchar(500)

);

--para evitar q se duplique la misma subcategoria en un presupuesto
create unique index presupuesto_unico on PRESUPUESTO_DETALLE (Id_presupuesto,Id_subcategoria);

create table OBLIGACION_FIJA
(

    Id_obligacion_fija bigint generated by default as identity primary key,
    Id_usuario bigint not null,
    Id_subcategoria bigint not null,--en obligacion fija la subcategoria siempre es de tipo gasto OJOOOO AQUIIIIIII
    Nombre varchar(70) not null,
    Descripcion_detallada varchar(500)not null,
    Monto_fijo_mensual decimal(14,2)not null,
    Dia_del_mes_de_vencimiento smallint not null,--1...31
    Esta_vigente boolean not null default true,
    Fecha_inicio_de_la_obligacion date not null,
    Fecha_de_inicializacion date 
    
);

create table TRANSACCION
(

    Id_transaccion bigint generated by default as identity primary key,
    Id_usuario bigint not null,
    Id_presupuesto bigint not null,
    Anio smallint not null,
    Mes smallint not null,
    Id_subcategoria bigint not null,
    Id_obligacion_fija bigint,--opcionallll
    Tipo_de_transaccion varchar(15)not null, --ingreso|gasto|ahorro
    Descripcion varchar(500),
    Monto decimal(14,2)not null,
    Fecha date not null,
    Metodo_de_pago varchar(30)not null,--efectivo|tarjeta_debito|tarjeta_credito|transferencia
    Fecha_hora_de_registro timestamp not null

);

/*

indices me serviran para acelerar las consultas que filtran por periodo y por presupuesto o subcategoria
funcionaran porque el motor puede localizar rapido los registros de transaccion usando el orden de las columnas
del indice

Optimiza consultas que fijan un presupuesto y luego filtran/ordenan por año/mes
Optimiza consultas que fijan una subcategoría y filtran/ordenan por año/mes

*/
create index presu_periodo on TRANSACCION (Id_presupuesto,Anio,Mes);
create index subcat_periodo on TRANSACCION(Id_subcategoria,Anio,Mes);

create table META_AHORRO
(

    Id_Ahorro bigint generated by default as identity primary key,
    Id_usuario bigint not null,
    Id_subcategoria bigint not null,--de tipo ahorrooooooooooooooo
    Nombre varchar(70)not null,
    Descripcion_detallada varchar(500),
    Monto_total_alcanzar decimal(14,2)not null,
    Monto_ahorrado decimal(14,2)not null,
    Fecha_inicio date not null,
    Fecha_objetivo date not null,
    Prioridad varchar(10)not null,--alta|media|baja de prioridad
    Estado varchar(10)not null--en_progreso|completada|cancelada|pausada
    
);

create table ALERTA
(

    Id_alerta bigint generated by default as identity primary key,
    Id_usuario bigint not null,
    Id_presupuesto_detalle bigint,--opcional
    Id_obligacion_fija bigint,--opcional
    Tipo_de_alerta varchar(80)not null,--presupuesto_80: Se alcanzó el 80% del presupuesto en una categoría - presupuesto_100: Se alcanzó el 100% del presupuesto en una categoría - presupuesto_excedido: Se excedió el presupuesto en una categoría - vencimiento_proximo: Obligación próxima a vencer (3 días antes) - vencimiento_vencida: Obligación vencida sin registro de pago - meta_50: Se alcanzó el 50% de una meta de ahorro -  meta_completada: Se completó una meta de ahorro -  ingreso_menor: Los ingresos del mes están por debajo del promedio
    Titulo varchar(80)not null,
    Mensaje_descriptivo varchar(500)not null,
    Nivel_de_prioridad varchar(12)not null,--informativa|advertencia|critica
    Fecha_hora_de_creacion timestamp not null,
    indicador_vista_usuario boolean not null default false,
    Fecha_hora timestamp

);

--RELACIONES 
alter table PRESUPUESTO add constraint fk_presupuesto_usuario foreign key (Id_usuario) references USUARIOS(Id_usuario);

alter table META_AHORRO add constraint fk_meta_usuario foreign key(Id_usuario) references USUARIOS(Id_usuario);

alter table OBLIGACION_FIJA add constraint fk_obligacion_usuario foreign key(Id_usuario) references USUARIOS(Id_usuario);

alter table TRANSACCION add constraint fk_transaccion_usuario foreign key(Id_usuario)references USUARIOS(Id_usuario);

alter table ALERTA add constraint fk_alerta_usuario foreign key(Id_usuario)references USUARIOS(Id_usuario);

alter table SUBCATEGORIA add constraint fk_subcat_categoria foreign key(Id_categoria)references CATEGORIA(Id_categoria);

alter table PRESUPUESTO_DETALLE add constraint fk_pdet_presupuesto foreign key(Id_presupuesto)references PRESUPUESTO(Id_presupuesto);

alter table PRESUPUESTO_DETALLE add constraint fk_presupuesto_subcategoria foreign key(Id_subcategoria)references SUBCATEGORIA(Id_subcategoria);

alter table OBLIGACION_FIJA add constraint fk_obligacion_subcategoria foreign key(Id_subcategoria)references SUBCATEGORIA(Id_subcategoria);

alter table TRANSACCION add constraint fk_transaccion_de_subcategoria foreign key(Id_subcategoria)references SUBCATEGORIA(Id_subcategoria);

alter table META_AHORRO add constraint fk_meta_subcategoria foreign key(Id_subcategoria)references SUBCATEGORIA(Id_subcategoria);

alter table TRANSACCION add constraint fk_transaccion_presupuesto foreign key(Id_presupuesto)references PRESUPUESTO(Id_Presupuesto);

alter table ALERTA add constraint fk_alerta_detalle foreign key(Id_presupuesto_detalle)references PRESUPUESTO_DETALLE(Id_presupuesto_detalle);

alter table TRANSACCION add constraint fk_transaccion_obligacion foreign key(Id_obligacion_fija)references OBLIGACION_FIJA(Id_obligacion_fija);

alter table ALERTA add constraint fk_alerta_obligacion foreign key(Id_obligacion_fija)references OBLIGACION_FIJA(Id_obligacion_fija);


--RESTRICCIONES

/*
usare "check" para cumplir reglas logicas que debe cumplirse para cada fila y columna
si la condicion no se cumple, el INSERT/UPDATE falla con error.

tambien usare "between", es un operador para decir "entre A y B incluyendo los extremos".
lo usare para los meses 1..12 y para los dias 1....31

*/
alter table TRANSACCION add constraint ck_mes check(MES between 1 and 12);

alter table OBLIGACION_FIJA add constraint ck_dia check(Dia_del_mes_de_vencimiento between 1 and 31);



